# UTS-1 All About Me

Keira Amelie Hanayesha, seorang mahasiswi ITB, angkatan 2024, jurusan Sistem dan Teknologi Informasi, kelas ganjil, nim 18224003

Mungkin hanya sampai di situ teman-teman dan kenalan akrab mengenalku. Sebuah nama, angkatan, dan label jurusan yang terasa sangat teknis dan formal. Tetapi, seperti halnya sebuah code yang memiliki banyak lapisan tersembunyi, perkenalan singkat itu tidak cukup untuk mendefinisikan siapa aku sebenarnya. So, let me reintroduce myself.

Aku Keira, anak STI'24 yang, sejujurnya, merasa biasa-biasa saja di antara deretan mahasiswa jenius Ganesha. Hari-hariku saat ini memang diisi dengan alogaritma, pemodelan data, dan tantangan merancang sistem yang efisien. Namun, jika ada yang bertanya tentang minat terdalamku, sejujurnya aku ingin sekali menjawab: musik.

Banyak yang mungkin tidak tahu, di balik layar laptop yang menampilkan barisan syntax dan diagram ER, aku adalah seorang penikmat setia budaya pop yang dinamis, terutama Anime dan K-Pop. Dan jujur saja, dari K-Pop inilah aku menemukan passion terbesarku. Ritme yang kompleks, visual yang menawan, dan dedikasi para artis dalam menyanyi dan menari telah membuka mata dan jiwaku terhadap seni musik yang sesungguhnya.

Musik bukan sekadar hobi; itu adalah ruang pelarian dan ekspresi diri yang paling autentik. Di sinilah cita-cita dan mimpiku yang sesungguhnya bersemi: untuk suatu hari nanti, aku bisa merilis musikku sendiri.