name: Deploy Quarto
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render Quarto
        run: quarto render --to html
      
      - name: Auto Commit Docs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Auto-update docs from Quarto build" || exit 0
          git push
